name: CMake Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the GitHub Actions interface

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: gcc

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Clean previous build and cache files
        run: |
          rm -rf build
          rm -f CMakeCache.txt
          mkdir build

      - name: Install Raylib on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev
          git clone https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install

      - name: Install Raylib on macOS
        if: matrix.os == 'macos-latest'
        run: brew install raylib

      - name: Install Raylib on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y raylib

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.compiler == 'gcc' ? 'gcc' : 'clang' }} \
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --output-on-failure -C Debug
